site_name: {{VaultName}}
site_description: {{VaultDescription}}
site_author: {{VaultAuthor}}
site_url: {{VaultURL}}
copyright: Copyright &copy; 2023 {{VaultAuthor}}
repo_url: https://github.com/{{VaultAuthorGitHubUser}}/{{VaultName}}/
repo_name: {{VaultAuthorGitHubUser}}/{{VaultName}}
remote_branch: gh-pages
edit_uri: edit/main/
use_directory_urls: true
docs_dir: .docs

theme:
  name: 'material'
  features:
    - navigation.tabs
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - toc:
      permalink: true
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.smartsymbols
  - meta
  - smarty
  - fontawesome_markdown

plugins:
  - search
  # - roamlinks
  - awesome-pages
